# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [5]:
import numpy as np

In [1]:
l = [
    [1, 2, 3],
    [10,20,30]
]
l

[[1, 2, 3], [10, 20, 30]]

In [3]:
l[0]

[1, 2, 3]

In [4]:
l[0][0]

1

In [7]:
al = np.array(l)
al

array([[ 1,  2,  3],
       [10, 20, 30]])

In [9]:
al[0, 1]  # [0축의 index, 1축의 index]

2

In [24]:
a2 = np.arange(12).reshape((2,2,3))
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [173]:
a2[0,1,2]

5

In [183]:
np.random.seed(0)
aa = np.random.randint(1,11,size=(10))
aa

array([ 6,  1,  4,  4,  8, 10,  4,  6,  3,  5])

In [184]:
aa[[0,1,2]]   # 해당 index의 값들을 가져옴

array([6, 1, 4])

In [156]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
# fancy indexing = 한번에 여러개 값을 조회
# 2, 5, 7
# a[2,5,7]  # 0축:2, 1축:5, 2축:7
a[[2,5,7]]  # 리스트로 조회할 index들을 묶어준다

array([2, 5, 7])

In [27]:
arr = np.array([[1,2,3],[10,20,30]])
arr.shape

(2, 3)

In [29]:
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [30]:
arr[0,0]

1

In [31]:
# 배열[0축의 index,1축의 index]
arr[1,2]

30

In [32]:
arr[[0,0],[1,2]]     # [0,1]인덱스와 [0,2]인덱스가 조회된다

array([2, 3])

In [33]:
arr[[0,1],[0,2]]

array([ 1, 30])

In [34]:
arr[[0,1,1],[0,2,1]]

array([ 1, 30, 20])

In [35]:
print(a2.shape)
a2

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
#1, 8, 11
a2[[0,1,1],[0,0,1],[1,2,2]]

array([ 1,  8, 11])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [40]:
a = np.arange(100)
a.shape
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
a[10:50:2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [42]:
a[50::10]  # 50 ~ 끝, step : 10

array([50, 60, 70, 80, 90])

In [43]:
a[1:10:]   # 1~9 step 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
a[10:1:-1]   # 10 ~ 1 / step : -1 (증감치)
# step()

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [47]:
a[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [84]:
a = np.arange(48).reshape(6,8)
print(a.shape)
a

(6, 8)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [58]:
a[1:5,1:6]    # 0축 : 1 ~ 4 / 1축 : 1 ~ 5  / step:+1

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37]])

In [61]:
a[1:5,1::2]

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [62]:
a[:, [0,2]]  # 모든 행(0축)에서 0, 2열의 값(1축)만 조회

array([[ 0,  2],
       [ 8, 10],
       [16, 18],
       [24, 26],
       [32, 34],
       [40, 42]])

In [63]:
a[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [85]:
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [86]:
# 슬라이싱한 값을 바꾸면 원래 array의 값도 바뀐다!! sql의 view 처럼!!
b = a[1:5,1:6]
b

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37]])

In [87]:
b[0,0] = 200
b

array([[200,  10,  11,  12,  13],
       [ 17,  18,  19,  20,  21],
       [ 25,  26,  27,  28,  29],
       [ 33,  34,  35,  36,  37]])

In [88]:
# 원본인 a도 바뀌었다!!
a

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8, 200,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47]])

In [90]:
c = a[1:5,1:6].copy()   # ndarray.copy() => 배열을 복사
c

array([[200,  10,  11,  12,  13],
       [ 17,  18,  19,  20,  21],
       [ 25,  26,  27,  28,  29],
       [ 33,  34,  35,  36,  37]])

In [91]:
c[0,0]

200

In [92]:
c[0,0] = 10000000
c

array([[10000000,       10,       11,       12,       13],
       [      17,       18,       19,       20,       21],
       [      25,       26,       27,       28,       29],
       [      33,       34,       35,       36,       37]])

In [93]:
a

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8, 200,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47]])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [95]:
a = np.arange(3)
a

array([0, 1, 2])

In [98]:
b = [True, False, True]   # masking

In [99]:
a[b]

array([0, 2])

In [107]:
print(a + 10)

# 원소별로 연산
(a + 10) > 10

[10 11 12]


array([False,  True,  True])

In [105]:
a

array([0, 1, 2])

In [109]:
# 배열 a의 원소 중 1 이상인 값들만 조회 => 특정 조건을 만족하는 원소들만 조회할 때 boolean indexing을 사용
a[a>=1]

array([1, 2])

In [111]:
b = np.random.randint(100, size=100)
b

array([35,  1, 28, 29, 61, 29, 54, 61, 56,  9, 57, 95, 25, 35, 90, 56, 51,
       25, 71, 35, 29, 17, 59, 43, 52, 35, 67, 88, 58, 17, 46, 77, 92, 55,
       68,  9, 25, 38, 87, 76, 31,  4, 75, 70,  3, 53, 64, 17, 71, 71, 81,
        4, 92, 70, 32, 72, 63, 49, 23, 49, 50, 31, 18, 73, 93, 18, 18, 13,
       34, 46,  5, 90, 58, 15, 13, 53, 76, 29, 59, 33, 25, 52, 78, 11, 16,
       19,  2, 13, 85, 98, 81, 41, 48, 39, 80, 40, 74, 83,  8, 46])

In [114]:
c = b[b>=50]
c

array([61, 54, 61, 56, 57, 95, 90, 56, 51, 71, 59, 52, 67, 88, 58, 77, 92,
       55, 68, 87, 76, 75, 70, 53, 64, 71, 71, 81, 92, 70, 72, 63, 50, 73,
       93, 90, 58, 53, 76, 59, 52, 78, 85, 98, 81, 80, 74, 83])

In [116]:
c.shape

(48,)

In [117]:
b2 = b.reshape(2,50)
print(b2.shape)
b2

(2, 50)


array([[35,  1, 28, 29, 61, 29, 54, 61, 56,  9, 57, 95, 25, 35, 90, 56,
        51, 25, 71, 35, 29, 17, 59, 43, 52, 35, 67, 88, 58, 17, 46, 77,
        92, 55, 68,  9, 25, 38, 87, 76, 31,  4, 75, 70,  3, 53, 64, 17,
        71, 71],
       [81,  4, 92, 70, 32, 72, 63, 49, 23, 49, 50, 31, 18, 73, 93, 18,
        18, 13, 34, 46,  5, 90, 58, 15, 13, 53, 76, 29, 59, 33, 25, 52,
        78, 11, 16, 19,  2, 13, 85, 98, 81, 41, 48, 39, 80, 40, 74, 83,
         8, 46]])

In [118]:
b2[b2>=50]   # ND array에 boolean indexing을 적용하면 True값들만 1차원 배열에 모아서 반환

array([61, 54, 61, 56, 57, 95, 90, 56, 51, 71, 59, 52, 67, 88, 58, 77, 92,
       55, 68, 87, 76, 75, 70, 53, 64, 71, 71, 81, 92, 70, 72, 63, 50, 73,
       93, 90, 58, 53, 76, 59, 52, 78, 85, 98, 81, 80, 74, 83])

In [120]:
# 50 ~ 70 사이의 정수?
# numpy 논리연산자의 경우 파이썬의 and, or는 사용할 수 없다.
# and: &   /  or: |   / not: ~
# 피연산자는 반드시 ()로 묶어줘야한다.

# b>=50 and b<=70 : numpy에서는 성립 X
b[(b>=50) & (b<=70)]

array([61, 54, 61, 56, 57, 56, 51, 59, 52, 67, 58, 55, 68, 70, 53, 64, 70,
       63, 50, 58, 53, 59, 52])

In [121]:
# 파이썬에서는 성립 but numpy에서는 성립 X
x = 7
50 <= x <= 70

False

In [122]:
b>50

array([False, False, False, False,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True, False,
        True, False, False, False,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
        True, False, False,  True,  True, False,  True, False, False,
        True,  True, False, False, False, False, False,  True,  True,
        True, False, False, False,  True, False,  True,  True, False,
       False])

In [124]:
~(b>50)

array([ True,  True,  True,  True, False,  True, False, False, False,
        True, False, False,  True,  True, False, False, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
       False, False,  True,  True, False, False, False, False,  True,
        True,  True, False, False,  True,  True, False, False,  True,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False, False,  True, False,  True,  True,
       False, False,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True, False,  True, False, False,  True,
        True])

In [125]:
# 50 이하인 값
b[~(b>50)]

array([35,  1, 28, 29, 29,  9, 25, 35, 25, 35, 29, 17, 43, 35, 17, 46,  9,
       25, 38, 31,  4,  3, 17,  4, 32, 49, 23, 49, 50, 31, 18, 18, 18, 13,
       34, 46,  5, 15, 13, 29, 33, 25, 11, 16, 19,  2, 13, 41, 48, 39, 40,
        8, 46])

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [130]:
l = [True, False, True]

In [131]:
np.where(l) # 리스트에서 True값들의 index들을 반환

(array([0, 2], dtype=int64),)

In [132]:
np.where(l,'참','거짓')  # True ->'참', False -> '거짓'

array(['참', '거짓', '참'], dtype='<U2')

In [134]:
np.where(l, '참', l)

array(['참', 'False', '참'], dtype='<U5')

In [136]:
b

array([35,  1, 28, 29, 61, 29, 54, 61, 56,  9, 57, 95, 25, 35, 90, 56, 51,
       25, 71, 35, 29, 17, 59, 43, 52, 35, 67, 88, 58, 17, 46, 77, 92, 55,
       68,  9, 25, 38, 87, 76, 31,  4, 75, 70,  3, 53, 64, 17, 71, 71, 81,
        4, 92, 70, 32, 72, 63, 49, 23, 49, 50, 31, 18, 73, 93, 18, 18, 13,
       34, 46,  5, 90, 58, 15, 13, 53, 76, 29, 59, 33, 25, 52, 78, 11, 16,
       19,  2, 13, 85, 98, 81, 41, 48, 39, 80, 40, 74, 83,  8, 46])

In [138]:
np.where(b >= 50, '50이상', '50미만')

array(['50미만', '50미만', '50미만', '50미만', '50이상', '50미만', '50이상', '50이상',
       '50이상', '50미만', '50이상', '50이상', '50미만', '50미만', '50이상', '50이상',
       '50이상', '50미만', '50이상', '50미만', '50미만', '50미만', '50이상', '50미만',
       '50이상', '50미만', '50이상', '50이상', '50이상', '50미만', '50미만', '50이상',
       '50이상', '50이상', '50이상', '50미만', '50미만', '50미만', '50이상', '50이상',
       '50미만', '50미만', '50이상', '50이상', '50미만', '50이상', '50이상', '50미만',
       '50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50미만', '50이상',
       '50이상', '50미만', '50미만', '50미만', '50이상', '50미만', '50미만', '50이상',
       '50이상', '50미만', '50미만', '50미만', '50미만', '50미만', '50미만', '50이상',
       '50이상', '50미만', '50미만', '50이상', '50이상', '50미만', '50이상', '50미만',
       '50미만', '50이상', '50이상', '50미만', '50미만', '50미만', '50미만', '50미만',
       '50이상', '50이상', '50이상', '50미만', '50미만', '50미만', '50이상', '50미만',
       '50이상', '50이상', '50미만', '50미만'], dtype='<U4')

In [141]:
np.where(b>=50)  # b의 원소 중 50이상인 값들의 **index** 조회

(array([ 4,  6,  7,  8, 10, 11, 14, 15, 16, 18, 22, 24, 26, 27, 28, 31, 32,
        33, 34, 38, 39, 42, 43, 45, 46, 48, 49, 50, 52, 53, 55, 56, 60, 63,
        64, 71, 72, 75, 76, 78, 81, 82, 88, 89, 90, 94, 96, 97],
       dtype=int64),)

In [142]:
np.where(b>=70)

(array([11, 14, 18, 27, 31, 32, 38, 39, 42, 43, 48, 49, 50, 52, 53, 55, 63,
        64, 71, 76, 82, 88, 89, 90, 94, 96, 97], dtype=int64),)

In [140]:
# 70이상인 값들은 모두 70으로 변환, 70미만은 그대로 유지
np.where(b>=70,70,b)

array([35,  1, 28, 29, 61, 29, 54, 61, 56,  9, 57, 70, 25, 35, 70, 56, 51,
       25, 70, 35, 29, 17, 59, 43, 52, 35, 67, 70, 58, 17, 46, 70, 70, 55,
       68,  9, 25, 38, 70, 70, 31,  4, 70, 70,  3, 53, 64, 17, 70, 70, 70,
        4, 70, 70, 32, 70, 63, 49, 23, 49, 50, 31, 18, 70, 70, 18, 18, 13,
       34, 46,  5, 70, 58, 15, 13, 53, 70, 29, 59, 33, 25, 52, 70, 11, 16,
       19,  2, 13, 70, 70, 70, 41, 48, 39, 70, 40, 70, 70,  8, 46])

In [144]:
c = np.arange(12).reshape(3,4)
print(c.shape)
c

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
np.where(c>5)   # c에서 5 초과인 값들의 index 출력

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [147]:
d = np.arange(12).reshape(2,2,3)
print(d.shape)

(2, 2, 3)


In [148]:
np.where(d>7)

(array([1, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 1], dtype=int64),
 array([2, 0, 1, 2], dtype=int64))

- 2차원도 마찬가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [158]:
np.any(b >= 99) #배열 b에 99이상인 값이 하나라도 있는지 여부?

False

In [159]:
np.any(b >= 90)

True

In [160]:
np.all(b>=90) # 배열 b의 모든 원소들이 90 이상인지 여부?

False

In [161]:
np.all(b>=0)

True

### 정렬
- np.sort(arr): arr을 정렬
- np.argsort(arr): 정렬 후 index를 반환

In [162]:
x = np.array([4, 1, 6, 9, 2])
x

array([4, 1, 6, 9, 2])

In [163]:
y = np.sort(x) #x를 정렬한 원소들을 가지는 새로운 배열을 반환
y

array([1, 2, 4, 6, 9])

In [164]:
x

array([4, 1, 6, 9, 2])

In [165]:
x.sort() #배열 x(원본) 자체를 정렬

In [166]:
x

array([1, 2, 4, 6, 9])

In [167]:
z = np.array([4, 1, 6, 9, 2])
# 내림차순 정렬 -> slicing이용
np.sort(z)[::-1]

array([9, 6, 4, 2, 1])

In [168]:
-np.sort(-z)

array([9, 6, 4, 2, 1])

In [169]:
a = np.array([0.1, 0.7, 0.4])
# 오름차순 정렬했을때 먼저오는 index
# 0, 2, 1

In [170]:
sort_idx = np.argsort(a)
sort_idx

array([0, 2, 1], dtype=int64)

In [171]:
a[sort_idx]

array([0.1, 0.4, 0.7])

In [172]:
# 다차원 배열 정렬
# np.sort(배열, axis=기준축) 기준축 생략시 마지막 축을 기준으로 정렬

In [150]:
l = [
    [1, 0, 5],
    [0, 10, 2],
    [8, 7, 6]
]
arr = np.array(l)
arr.shape

(3, 3)

In [151]:
arr

array([[ 1,  0,  5],
       [ 0, 10,  2],
       [ 8,  7,  6]])

In [152]:
np.sort(arr, axis=0)

array([[ 0,  0,  2],
       [ 1,  7,  5],
       [ 8, 10,  6]])

In [153]:
np.sort(arr, axis=1)

array([[ 0,  1,  5],
       [ 0,  2, 10],
       [ 6,  7,  8]])

In [154]:
np.sort(arr)

array([[ 0,  1,  5],
       [ 0,  2, 10],
       [ 6,  7,  8]])