# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.

In [1]:
import numpy as np

In [4]:
x = np.arange(20)
print(x.shape)
x

(20,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
r1 = np.reshape(x,(4,5))
print(r1.shape)
r1

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
r2 = np.reshape(x,(2,2,5))
print(r2.shape)
r2

(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [15]:
r3 = x.reshape((2,2,5))
r3 = x.reshape(2,2,5)   # 위와 같은 표현!!
r3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# 원본 배열의 size와 reshape size는 동일해야한다!
x.reshape(2,3,3)

ValueError: cannot reshape array of size 20 into shape (2,3,3)

In [18]:
x.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
# 나머지 하나값을 -1로 설정하면 알아서 맞춰서 설정됨!!
x.reshape(4,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
x.reshape(1,-1)    # (20,)  -> (1,20) 2차원 배열이 됨  =  더미 축(축만 늘림)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [27]:
x.reshape(1,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [24]:
x.reshape(4,1,5)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])

In [25]:
x.reshape(4,5,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [ ]:
# (20,) -> (1,20) , (1,1,1,1,1,1,1,1,20,1)

## 차원 늘리기(확장)
- dummy axis를 추가
    - dummy axis : size가 1인 axis(축)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 rank를 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    

In [28]:
x.shape

(20,)

In [ ]:
(20,) -> (20,1)
      -> (1,20)

In [29]:
r = x[:, np.newaxis]
print(r.shape)
r

(20, 1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [32]:
r = x[np.newaxis,:]
print(r.shape)
r

(1, 20)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [33]:
# ...은 축을 늘릴때만 사용하는 표현!!
r2 = x[...,np.newaxis]
print(r2.shape)

(20, 1)


In [34]:
r2 = x[np.newaxis,...]  #(1,20)
r2.shape

(1, 20)

In [35]:
r3 = x[np.newaxis, np.newaxis,...]
r3.shape

(1, 1, 20)

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [36]:
x = np.arange(12).reshape(3,4)
x.shape

(3, 4)

In [41]:
# (3,4)  => (3,1,4)
r = x[:,np.newaxis ,:]
print(r.shape)
r

(3, 1, 4)


array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [44]:
rr = x[:,np.newaxis , : , np.newaxis]
rr.shape

(3, 1, 4, 1)

In [45]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
# 마지막 or 첫번째에 더미축 추가
print(x[...,np.newaxis].shape)
print(x[np.newaxis,...].shape)

(3, 4, 1)
(1, 3, 4)


### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.

In [49]:
x.shape

(3, 4)

In [52]:
# (3,4) => (1,3,4)
# x[np.newaxis,...]
r = np.expand_dims(x,axis=0)
r.shape

(1, 3, 4)

In [53]:
# (3,4) => (3,1,4)
r = np.expand_dims(x,axis=1)
r.shape

(3, 1, 4)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다. (dummy axis 만 제거가능!)
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [55]:
x = np.arange(12).reshape(3,1,4,1,1)
x.shape

(3, 1, 4, 1, 1)

In [56]:
r = x.squeeze() #axis를 생략 -> None ->모든 dummy axis를 제거
r.shape

(3, 4)

In [63]:
r = x.squeeze(axis=1)
r.shape

(3, 4, 1, 1)

In [69]:
# axis는 정수값만 가능! 리스트형태는 안됨!! BUT 튜플형태로는 넣어진다!!
# r = x.squeeze(axis=[1,3])      # error
r = x.squeeze(axis=(1,3))
r.shape

(3, 4, 1)

In [67]:
# 튜플형태로 넣어주면 axis 여러개 한꺼번에 제거가능
r = np.squeeze(x,(1,3))
r.shape

(3, 4, 1)

In [58]:
# axis=0은 size가 1 이 아니므로 삭제가 안된다! => error 
x.squeeze(axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [60]:
print(x.shape)
x

(3, 1, 4, 1, 1)


array([[[[[ 0]],

         [[ 1]],

         [[ 2]],

         [[ 3]]]],



       [[[[ 4]],

         [[ 5]],

         [[ 6]],

         [[ 7]]]],



       [[[[ 8]],

         [[ 9]],

         [[10]],

         [[11]]]]])

In [62]:
r = x.flatten()
print(r.shape)
r

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [75]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [76]:
r = np.append(a,100)  # 원본은 그대로 둔 상태에서 값을 추가한 새로운 배열을 만든다.
r

array([  1,   2,   3, 100])

In [77]:
a

array([1, 2, 3])

In [78]:
r = np.append(a,[10,20,30])  # 한번에 여러개 값을 추가
r

array([ 1,  2,  3, 10, 20, 30])

In [84]:
b = np.arange(12).reshape(3,4)
print(b.shape)
b

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
np.append(b,100)  # axis를 지정하지 않음 => 1차원 배열로 만들어버림(flatten해버림)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100])

In [91]:
# axis=1 에 값들이 추가되어 shape값도 달라짐!!
print(np.append(b,[[100],[200],[300]], axis=1))
print(np.append(b,[[100],[200],[300]], axis=1).shape)

[[  0   1   2   3 100]
 [  4   5   6   7 200]
 [  8   9  10  11 300]]
(3, 5)


In [94]:
# axis=0 에 값들이 추가되어 shape값도 달라짐!!
print(np.append(b,[[100,200,300,400]], axis=0))
print(np.append(b,[[100,200,300,400]], axis=0).shape)

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 200 300 400]]
(4, 4)


In [95]:
# 여러 값을 한번에 넣는것도 가능!!
np.append(b,[[100,200,300,400],[11,22,33,44]],axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [100, 200, 300, 400],
       [ 11,  22,  33,  44]])

### insert(배열, index, 추가할값, axis=None)
   - 배열의 index에 추가할값을 추가. 
   - axis : 축 지정
       - None(기본값) : flatten 한 뒤 삽입한다.

In [96]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [100]:
# [1,100,2,3]
r = np.insert(a,1,100)  # index 1에 100 삽입
r

array([  1, 100,   2,   3])

In [102]:
# 여러개 값을 한번에 삽입
r = np.insert(a,1,[10,20,30,40])
r

array([ 1, 10, 20, 30, 40,  2,  3])

In [103]:
l = [
    [1,1],
    [2,2],
    [3,3]
]
b = np.array(l)
print(b.shape)
b

(3, 2)


array([[1, 1],
       [2, 2],
       [3, 3]])

In [118]:
np.insert(b,2,[[100]],axis=1)

array([[  1,   1, 100],
       [  2,   2, 100],
       [  3,   3, 100]])

In [120]:
np.insert(b,1,5,axis=1)  # 동일한 값을 넣을 경우 정수

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [128]:
np.insert(b,1,[[5,50,500]],axis=1)

array([[  1,   5,   1],
       [  2,  50,   2],
       [  3, 500,   3]])

In [129]:
np.insert(b,1,[[100],[200]],axis=1)

array([[  1, 100, 200,   1],
       [  2, 100, 200,   2],
       [  3, 100, 200,   3]])

In [130]:
np.insert(b,1,[[100,500,600],[200,700,800]],axis=1)

array([[  1, 100, 200,   1],
       [  2, 500, 700,   2],
       [  3, 600, 800,   3]])

In [114]:
np.insert(b,2,[[100]],axis=0)

array([[  1,   1],
       [  2,   2],
       [100, 100],
       [  3,   3]])

In [117]:
np.insert(b,2,[[100,100],[200,201]],axis=0)

array([[  1,   1],
       [  2,   2],
       [100, 100],
       [200, 201],
       [  3,   3]])

### delete(배열, 삭제할index, axis=None)  
   - 배열의 삭제할index의 값들을 삭제한다.
   - 삭제할 index는 index 또는 slice
   - axis : 축 지정
       - None(기본값) : flatten 한 뒤 삭제한다.

In [132]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
r = np.delete(a,1)
r

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [134]:
r = np.delete(a,[1,7,8])  # 여러 index삭제시 []로 묶어준다
r

array([ 0,  2,  3,  4,  5,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [139]:
# np.s_[slicing문법] : 배열과 상관없이 slicing 범위만 지정할 때 사용하는 numpy 변수 
r = np.delete(a,np.s_[2:11:2])
r

array([ 0,  1,  3,  5,  7,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [141]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [142]:
np.delete(b,1) # 다차원배열에서 axis를 지정안하면 flatten 후 삭제

array([1, 2, 2, 3, 3])

In [144]:
np.delete(b,1,axis=1)

array([[1],
       [2],
       [3]])

In [145]:
np.delete(b,1,axis=0)

array([[1, 1],
       [3, 3]])

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(2,6)
b = np.arange(10,22).reshape(2,6)
c = np.arange(20,32).reshape(2,6)
a.shape, b.shape, c.shape

((2, 6), (2, 6), (2, 6))

In [4]:
r = np.concatenate([a, b], axis=0) # 배열 a와 b를 합친다. 기준축은 0번축
r.shape

(4, 6)

In [6]:
r2 = np.concatenate([a,b,c], axis=0)
r2.shape

(6, 6)

In [7]:
r2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [9]:
r3 = np.concatenate([a,b,c], axis=1)
r3.shape

(2, 18)

In [10]:
r3

array([[ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23,
        24, 25],
       [ 6,  7,  8,  9, 10, 11, 16, 17, 18, 19, 20, 21, 26, 27, 28, 29,
        30, 31]])

In [11]:
x = np.arange(12).reshape(2,2,3)
y = np.arange(10,26).reshape(2,2,4)
x.shape, y.shape

((2, 2, 3), (2, 2, 4))

In [12]:
# axis=0 과 axis=1을 기준으로 합치면 axis=2의 값이 다르기 때문에 합쳐지지 않는다
r4 = np.concatenate([x,y],axis=2)
r4.shape

(2, 2, 7)

In [13]:
r4

array([[[ 0,  1,  2, 10, 11, 12, 13],
        [ 3,  4,  5, 14, 15, 16, 17]],

       [[ 6,  7,  8, 18, 19, 20, 21],
        [ 9, 10, 11, 22, 23, 24, 25]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [15]:
v1 = np.vstack([a,b,c])  # axis=0기준으로 합친다
v1.shape

(6, 6)

In [16]:
np.vstack?

In [17]:
# 다차원도 가능은 하지만 주로 2차원(행렬)에 사용한다!
x = np.arange(12).reshape(2,2,3)
y = np.arange(12).reshape(2,2,3)
v2 = np.vstack([x,y])
v2.shape

(4, 2, 3)

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

In [19]:
h1 = np.hstack([a,b,c])
h1.shape

(2, 18)

In [20]:
h2 = np.hstack([x,y])
h2.shape

(2, 4, 3)

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [22]:
a = np.arange(10)
a.shape


(10,)

In [23]:
r = np.split(a,2,axis=0)   # 두개의 배열로 나눠라, 나눠진 두 배열의 기준축의 size는 동일
r

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [28]:
print(type(r))
r

<class 'list'>


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [27]:
r3 = np.split(a,5)
print(len(r3))
r3

5


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [29]:
r2 = np.split(a,3)

ValueError: array split does not result in an equal division

In [32]:
# 인덱스를 기준으로 자르기(기준인덱스 앞에서 자름)
r4 = np.split(a,[3,7])
print(len(r4))
r4

3


[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [35]:
b = np.arange(48).reshape(8,6)
print(b.shape)
b

(8, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [38]:
r = np.split(b,2,axis=0)
print(len(r))
print(r)
r[0].shape, r[1].shape

2
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])]


((4, 6), (4, 6))

In [39]:
r = np.split(b,3,axis=1)
print(len(r))
r[0].shape, r[1].shape, r[2].shape

3


((8, 2), (8, 2), (8, 2))

In [40]:
r[0]

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31],
       [36, 37],
       [42, 43]])

In [42]:
b.shape

(8, 6)

In [43]:
r = np.split(b, [2,5],axis=0)
len(r)

3

In [44]:
r[0].shape, r[1].shape, r[2].shape

((2, 6), (3, 6), (3, 6))

In [45]:
c = np.arange(4*4*8).reshape(4,4,8)
c.shape

(4, 4, 8)

In [47]:
r = np.split(c, 2, axis=0)
len(r)

2

In [48]:
r[0].shape, r[1].shape

((2, 4, 8), (2, 4, 8))

In [50]:
r = np.split(c, [3,6], axis=2)
len(r)

3

In [51]:
x,y,z = r
x.shape, y.shape, z.shape

((4, 4, 3), (4, 4, 3), (4, 4, 2))

## hsplit()/vsplit()
- vsplit() : axis=0
- hsplit() : axis=1
- 행렬(2차원 배열)용 함수, 다차원배열에도 사용가능

In [52]:
b.shape

(8, 6)

In [53]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [63]:
r = np.hsplit(b,3)
print(len(r))
x,y,z = r
x.shape, y.shape, z.shape

3


((8, 2), (8, 2), (8, 2))

In [60]:
r = np.vsplit(b,2)
print(len(r))
x,y = r
print(x)
x.shape, y.shape

2
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


((4, 6), (4, 6))

In [61]:
r = np.vsplit(b, [2,5,7])
print(len(r))
w,x,y,z = r
w.shape, x.shape, y.shape, z.shape

4


((2, 6), (3, 6), (2, 6), (1, 6))

In [64]:
w

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])